import { NextPage } from "next";

import { useCart } from "@/core/hooks/useCart";
import { getProducts, useProducts } from "@/core/hooks/useProducts";
import { LoadingSpinner } from "@/modules/UI/LoadingSpinner";
import { HeroSection } from "@/modules/home/HeroSection";
import { HomePage } from "@/modules/home/HomePage";
import { QueryClient, dehydrate } from "@tanstack/react-query";
import Head from "next/head";

const Home: NextPage = () => {
  const { data: products, isLoading, error } = useProducts();

  const { data } = useCart();

  if (isLoading) return <LoadingSpinner />;

  if (error) return <p>'An error has occurred:{error.message}'</p>;

  return (
    <div>
      <Head>
        <title>Reia - massage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <HeroSection />
        <HomePage products={products} />
      </div>
    </div>
  );
};

export default Home;

export async function getStaticProps() {
  const queryClient = new QueryClient();

  await queryClient.prefetchQuery(["products"], getProducts);

  return {
    props: { dehydratedState: dehydrate(queryClient) },
  };
}
