import { dehydrate, QueryClient } from "@tanstack/react-query";
import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { useCart } from "../core/hooks/useCart";
import { getProducts, useProducts } from "../core/hooks/useProducts";

import { ProductItem } from "../modules/products/Product";
import { HeroSection } from "../modules/home/HeroSection";
import { LoadingSpinner } from "../modules/UI/LoadingSpinner";
import { Heading } from "../modules/home/Heading";
import { Button } from "@material-tailwind/react";

const Home: NextPage = () => {
  const { data: products, isLoading, error } = useProducts();

  const { data } = useCart();

  if (isLoading) return <LoadingSpinner />;

  if (error) return <p>'An error has occurred:{error.message}'</p>;

  return (
    <div>
      <Head>
        <title>Reia - massage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <HeroSection />
        <section className="mx-6 md:mx-20 py-10 text-center">
          <Heading />
          <div className="grid gap-x-10 grid-cols-1 md:grid-cols-2 lg:grid-cols-3 mt-6">
            {products.data.map((product) => (
              <ProductItem key={product.id} product={product} />
            ))}
          </div>
          <Button color="brown" className="w-36">
            <Link href="/products">See more</Link>
          </Button>
        </section>
      </div>
    </div>
  );
};

export default Home;

export async function getStaticProps() {
  const queryClient = new QueryClient();

  await queryClient.prefetchQuery(["products"], getProducts);

  return {
    props: { dehydratedState: dehydrate(queryClient) },
  };
}
