name: Cypress Tests

on:
  push:
    branches:
      - "master"
  pull_request:
  workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: ./ # use the explicit version number
        with:
          build: npm run build
          start: npm start
